version: '3.8'
services:
  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: database
    ports: 
    - 27017:27017
    volumes: 
    - mongodb_data_container:/data/db
    
volumes:
  mongodb_data_container: